-- Supabase SQL snippets (copy/paste into SQL editor)
-- NOTE: Adjust schema/space_id handling to your setup.

-- 1) Client logs table (for errors/diagnostics)
create table if not exists public.client_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  space_id text not null,
  type text not null,
  message text,
  stack text,
  href text,
  ua text
);

-- Optional: index for troubleshooting
create index if not exists client_logs_created_at_idx on public.client_logs (created_at desc);
create index if not exists client_logs_space_id_idx on public.client_logs (space_id, created_at desc);

-- RLS
alter table public.client_logs enable row level security;

-- Allow inserts from the app (public). Consider tightening later (edge function / rate limit).
create policy if not exists "client_logs_insert" on public.client_logs
for insert to anon, authenticated
with check (true);

-- 2) Tags support in recipes table (optional)
-- If you want tags persisted in backend:
alter table public.recipes
  add column if not exists tags jsonb not null default '[]'::jsonb;

-- 3) App settings (e.g. category colors) – optional
create table if not exists public.app_settings (
  space_id text not null,
  key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (space_id, key)
);

alter table public.app_settings enable row level security;

-- Allow read + upsert (public). Tighten if you add auth.
create policy if not exists "app_settings_select" on public.app_settings
for select to anon, authenticated using (true);

create policy if not exists "app_settings_insert" on public.app_settings
for insert to anon, authenticated with check (true);

create policy if not exists "app_settings_update" on public.app_settings
for update to anon, authenticated using (true) with check (true);
